// Generated by CoffeeScript 1.7.1
(function() {
  var ContentPreprocessor, cheerio, fs;

  ContentPreprocessor = require('../../src/preprocessor/ContentPreprocessor');

  cheerio = require('cheerio');

  fs = require('fs');

  exports.ContentPreprocessor = {
    'test preprocess faces to use absolute url': function(test) {
      return fs.readFile('./test/viewFixtures/reply.html', {
        encoding: 'utf8'
      }, function(err, data) {
        var $, contentPreprocessor, subDomain;
        test.expect(4);
        test.ifError(err);
        subDomain = "m1";
        contentPreprocessor = new ContentPreprocessor(subDomain);
        $ = cheerio.load(data);
        $('.ReplyBox').each(function() {
          var numberOfFaces;
          numberOfFaces = $('img[src^="/faces"]', this).length;
          test.ok(numberOfFaces !== 0);
          contentPreprocessor.preprocess(this, $);
          test.ok($('img[src^="/faces"]', this).length === 0);
          return test.ok($("img[src^=\"http://" + subDomain + ".hkgolden.com/faces\"]", this).length === numberOfFaces);
        });
        return test.done();
      });
    }
  };

}).call(this);

//# sourceMappingURL=ConetntPreprocessor_test.map
