// Generated by CoffeeScript 1.7.1
(function() {
  var MobileGoldenContentPreprocessor, cheerio, fs, getImageSourceFromAlt;

  MobileGoldenContentPreprocessor = require('../../index').MobileGoldenContentPreprocessor;

  cheerio = require('cheerio');

  getImageSourceFromAlt = require('../../src/utils/helper').getImageSourceFromAlt;

  fs = require('fs');

  exports.MobileGoldenContentPreprocessor = {
    'test preprocess .Image': function(test) {
      return fs.readFile('./test/viewFixtures/reply.html', {
        encoding: 'utf8'
      }, function(err, data) {
        var $, contentPreprocessor, subDomain;
        test.expect(5);
        test.ifError(err);
        subDomain = "m1";
        contentPreprocessor = new MobileGoldenContentPreprocessor(subDomain);
        $ = cheerio.load(data);
        $('.ReplyBox').each(function() {
          var originalAlt;
          test.ok($('img.Image', this).attr('ng-src') === void 0);
          test.ok($('img.Image', this).attr('onclick') !== void 0);
          originalAlt = $('img.Image', this).attr('alt');
          contentPreprocessor.preprocess(this, $);
          test.equal($('img.Image', this).attr('ng-src'), originalAlt.substring(originalAlt.indexOf(']') + 1, originalAlt.lastIndexOf('[')));
          return test.ok($('img.Image', this).attr('onclick') === void 0);
        });
        return test.done();
      });
    }
  };

}).call(this);

//# sourceMappingURL=MobileGoldenContentPreprocessor_test.map
