// Generated by CoffeeScript 1.7.1
(function() {
  var helper;

  helper = require('../src/utils/helper');

  exports.helper = {
    setUp: function(done) {
      return done();
    },
    tearDown: function(done) {
      return done();
    },
    'test extend objects': function(test) {
      var result;
      result = helper.extend({
        name: 'name'
      }, {
        age: 10
      });
      test.deepEqual(result, {
        name: 'name',
        age: 10
      });
      return test.done();
    }
  };

}).call(this);

//# sourceMappingURL=helper_test.map
