language: node_js
node_js:
- 'node'
- '6'
- '5'
deploy:
  provider: npm
  email: "mikechung4@gmail.com"
  api_key:
    secure: ISn6TSXuZuyTKq4MN8XrYK3tTNc4nh8bVas4DcD5ooJgRFSsyjHbMQAhlGADwT/3oZNaEluWkzfBnuC5qls2ftKqWCNLMKQtPVG198ig60GheRAvgnkrvCGrT3odzCn0T0e3ZeY2OKyvAcScYavMEKJYSMDNwjWl0LwbWbOX6fc=
  on:
    tags: true
