// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      'nodeunit': {
        all: 'test/**/*_test.js'
      }
    });
    grunt.loadNpmTasks('grunt-contrib-nodeunit');
    return grunt.registerTask('default', ['nodeunit']);
  };

}).call(this);

//# sourceMappingURL=gruntfile.map
