// Generated by CoffeeScript 1.7.1
(function() {
  var MobileGoldenParser;

  MobileGoldenParser = require('./src/MobileGoldenParser');

  module.exports.MobileGoldenParser = MobileGoldenParser;

}).call(this);

//# sourceMappingURL=index.map
