// Generated by CoffeeScript 1.7.1
(function() {
  var MobileGoldenParser;

  MobileGoldenParser = require('./src/MobileGoldenParser');

  module.exports.MobileGoldenParser = MobileGoldenParser;

  module.exports.ContentPreprossor = require('./src/preprocessor/ContentPreprocessor');

  module.exports.MobileGoldenContentPreprocessor = require('./src/preprocessor/MobileGoldenContentPreprocessor');

}).call(this);

//# sourceMappingURL=index.map
