// Generated by CoffeeScript 1.7.1
(function() {
  var MobileGoldenContentPreprocessor, ThreadParser, cheerio, domainList;

  cheerio = require("cheerio");

  domainList = require('../utils/domainList');

  MobileGoldenContentPreprocessor = require('../preprocessor/MobileGoldenContentPreprocessor');

  ThreadParser = (function() {
    function ThreadParser() {}

    ThreadParser.prototype.parse = function(responseBody, onCompleteCallback) {
      var $, contentPreprocessor, replies, result, subDomain;
      $ = cheerio.load(responseBody);
      subDomain = domainList[Math.floor(Math.random() * domainList.length)];
      contentPreprocessor = new MobileGoldenContentPreprocessor(subDomain);
      result = [];
      result.isNextPageAvailable = $('.View_PageSelectRight').text().trim() !== '';
      result.isPreviousPageAvailable = $('.View_PageSelectLeft').text().trim() !== '';
      result.totalNumberOfPage = $('option', $('select.View_PageSelect').get(0)).length - 2;
      result.title = $('.ViewTitle').text().trim();
      replies = $('.ReplyBox');
      replies.each(function() {
        var author, authorDom, contentDom, date, gender, getReplyIdFromDom, images, replyId;
        getReplyIdFromDom = function() {
          var quoteLink, quoteLinkPattern, rid;
          quoteLink = $('.ViewAuthorPanel a', this).attr('href');
          quoteLinkPattern = /(rid=[0-9]*)/g;
          rid = quoteLink.match(quoteLinkPattern)[0];
          return rid.substring(rid.indexOf('=') + 1);
        };
        contentPreprocessor.preprocess(this);
        authorDom = $('.ViewNameMale, .ViewNameFemale', this);
        if (authorDom.length > 0) {
          author = authorDom.text();
          gender = $('.ViewNameMale', this).length > 0 ? "male" : "female";
          date = $('.ViewDate', this).text().trim();
          contentDom = $($(this).children('div').get(1));
          replyId = getReplyIdFromDom.call(this);
          images = [];
          $('img.Image', contentDom).each(function() {
            var $this, imageSrc;
            $this = $(this);
            imageSrc = $this.attr('ng-src');
            return images.push(imageSrc);
          });
          return result.push({
            author: author,
            gender: gender,
            content: contentDom.html(),
            images: images,
            date: date,
            replyId: replyId
          });
        }
      });
      return onCompleteCallback(result);
    };

    return ThreadParser;

  })();

  module.exports = ThreadParser;

}).call(this);

//# sourceMappingURL=ThreadParser.map
