// Generated by CoffeeScript 1.7.1
(function() {
  var ContentPreprocessor;

  ContentPreprocessor = (function() {
    function ContentPreprocessor(subDomain) {
      this.subDomain = subDomain;
    }

    ContentPreprocessor.prototype.preprocess = function(ele, $) {
      var preprocessor;
      preprocessor = this;
      return $(ele).find('img[src^="/faces"]').each(function() {
        return preprocessor.prependDomainToImageSrc($(this));
      });
    };

    ContentPreprocessor.prototype.prependDomainToImageSrc = function(img) {
      var src;
      src = img.attr('src');
      return img.attr('src', "http://" + this.subDomain + ".hkgolden.com" + src);
    };

    return ContentPreprocessor;

  })();

  module.exports = ContentPreprocessor;

}).call(this);

//# sourceMappingURL=ContentPreprocessor.map
