// Generated by CoffeeScript 1.7.1
(function() {
  var ContentPreprocessor, MobileGoldenContentPreprocessor, cheerio,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cheerio = require('cheerio');

  ContentPreprocessor = require('./ContentPreprocessor');

  MobileGoldenContentPreprocessor = (function(_super) {
    __extends(MobileGoldenContentPreprocessor, _super);

    function MobileGoldenContentPreprocessor() {
      return MobileGoldenContentPreprocessor.__super__.constructor.apply(this, arguments);
    }

    MobileGoldenContentPreprocessor.prototype.preprocess = function(ele) {
      var $, preprocessor;
      MobileGoldenContentPreprocessor.__super__.preprocess.call(this, ele);
      $ = cheerio.load(ele);
      preprocessor = this;
      return $('img.Image').each(function() {
        var $this, imageSrc;
        $this = $(this);
        $this.removeAttr('onclick');
        preprocessor.prependDomainToImageSrc($this);
        imageSrc = $this.attr('alt');
        imageSrc = imageSrc.substring(imageSrc.indexOf(']') + 1, imageSrc.lastIndexOf('['));
        return $this.attr('ng-src', imageSrc);
      });
    };

    return MobileGoldenContentPreprocessor;

  })(ContentPreprocessor);

  module.exports = MobileGoldenContentPreprocessor;

}).call(this);

//# sourceMappingURL=MobileGoldenContentPreprocessor.map
