// Generated by CoffeeScript 1.7.1
(function() {
  var ContentPreprocessor, MobileGoldenContentPreprocessor, getImageSourceFromAlt,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContentPreprocessor = require('./ContentPreprocessor');

  getImageSourceFromAlt = require('../utils/helper').getImageSourceFromAlt;

  MobileGoldenContentPreprocessor = (function(_super) {
    __extends(MobileGoldenContentPreprocessor, _super);

    function MobileGoldenContentPreprocessor() {
      return MobileGoldenContentPreprocessor.__super__.constructor.apply(this, arguments);
    }

    MobileGoldenContentPreprocessor.prototype.preprocess = function(ele, $) {
      var preprocessor;
      MobileGoldenContentPreprocessor.__super__.preprocess.call(this, ele, $);
      preprocessor = this;
      return $(ele).find('img.Image').each(function() {
        var $this;
        $this = $(this);
        $this.removeAttr('onclick');
        preprocessor.prependDomainToImageSrc($this);
        return $this.attr('ng-src', getImageSourceFromAlt($this));
      });
    };

    return MobileGoldenContentPreprocessor;

  })(ContentPreprocessor);

  module.exports = MobileGoldenContentPreprocessor;

}).call(this);

//# sourceMappingURL=MobileGoldenContentPreprocessor.map
