// Generated by CoffeeScript 1.7.1
(function() {
  var extend,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty;

  extend = exports.extend = function() {
    var key, nextIterationSources, source, sources, target, val;
    target = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (!sources || sources.length === 0) {
      return target;
    }
    if (!target) {
      target = {};
    }
    source = sources[0], nextIterationSources = 2 <= sources.length ? __slice.call(sources, 1) : [];
    for (key in source) {
      if (!__hasProp.call(source, key)) continue;
      val = source[key];
      target[key] = val;
    }
    return extend.apply(this, [target].concat(nextIterationSources));
  };

}).call(this);

//# sourceMappingURL=helper.map
