// Generated by CoffeeScript 1.7.1
(function() {
  var extend;

  extend = exports.extend = function(object, properties) {
    var key, val;
    for (key in properties) {
      val = properties[key];
      object[key] = val;
    }
    return object;
  };

}).call(this);

//# sourceMappingURL=helper.map
