// Generated by CoffeeScript 1.7.1
(function() {
  var helper;

  helper = require('../../src/utils/helper');

  exports.helper = {
    'test extend objects': function(test) {
      var result;
      result = helper.extend({
        name: 'name'
      }, {
        age: 10
      });
      test.deepEqual(result, {
        name: 'name',
        age: 10
      });
      return test.done();
    },
    'test null target': function(test) {
      var result;
      result = helper.extend(null, {
        name: 'name'
      });
      test.deepEqual(result, {
        name: 'name'
      });
      result = helper.extend(void 0, {
        name: 'name'
      });
      test.deepEqual(result, {
        name: 'name'
      });
      return test.done();
    },
    'test no extendee': function(test) {
      var result;
      result = helper.extend({
        name: 'name'
      });
      test.deepEqual(result, {
        name: 'name'
      });
      return test.done();
    }
  };

}).call(this);

//# sourceMappingURL=helper_test.map
