// Generated by CoffeeScript 1.7.1
(function() {
  var ThreadParser, cheerio, getImageSourceFromAlt;

  cheerio = require("cheerio");

  getImageSourceFromAlt = require('../../utils/helper').getImageSourceFromAlt;

  ThreadParser = (function() {
    function ThreadParser(preprocessors) {
      this.preprocessors = preprocessors;
    }

    ThreadParser.prototype.parse = function(responseBody, onCompleteCallback) {
      var $, preprocessors, replies, result;
      $ = cheerio.load(responseBody);
      preprocessors = this.preprocessors;
      result = {
        isNextPageAvailable: $('.btn-page-next').length > 0,
        isPreviousPageAvailable: $('.btn-page-prev').length > 0,
        totalNumberOfPage: +$('.pageno').text().substring($('.pageno').text().lastIndexOf(' ')),
        title: $('#heading').text().trim(),
        replies: []
      };
      replies = $('.post');
      replies.each(function() {
        var author, authorDom, contentDom, contentPreprocessor, date, gender, getReplyIdFromDom, images, replyId, _i, _len;
        getReplyIdFromDom = function() {
          var id;
          id = $(this).attr('id');
          return id.substring(id.indexOf('_') + 1);
        };
        for (_i = 0, _len = preprocessors.length; _i < _len; _i++) {
          contentPreprocessor = preprocessors[_i];
          if (typeof contentPreprocessor === 'function') {
            contentPreprocessor(this, $);
          } else {
            if (contentPreprocessor != null) {
              if (typeof contentPreprocessor.preprocess === "function") {
                contentPreprocessor.preprocess(this, $);
              }
            }
          }
        }
        authorDom = $('.name_male, .name_female', this);
        if (authorDom.length > 0) {
          author = authorDom.text();
          gender = $('.name_male', this).length > 0 ? "male" : "female";
          date = $('.topic-time', this).text().trim();
          contentDom = $('.post-content2', this);
          replyId = getReplyIdFromDom.call(this);
          images = [];
          $('img.Image', contentDom).each(function() {
            var $this;
            $this = $(this);
            return images.push(getImageSourceFromAlt($this));
          });
          return result.replies.push({
            author: author,
            gender: gender,
            content: contentDom.html(),
            images: images,
            date: date,
            replyId: replyId
          });
        }
      });
      return onCompleteCallback(result);
    };

    return ThreadParser;

  })();

  module.exports = ThreadParser;

}).call(this);

//# sourceMappingURL=ThreadParser.map
