// Generated by CoffeeScript 1.7.1
(function() {
  var TopicListParser, cheerio;

  cheerio = require("cheerio");

  TopicListParser = (function() {
    function TopicListParser() {}

    TopicListParser.prototype.parse = function(responseBody, onCompleteCallback) {
      var $, result, topicDoms;
      $ = cheerio.load(responseBody);
      topicDoms = $('.TopicBox_Details');
      result = {
        isNextPageAvailable: $('.View_PageSelectRight').text().trim() !== '',
        isPreviousPageAvailable: $('.View_PageSelectLeft').text().trim() !== '',
        totalNumberOfPage: $('option', $('select.View_PageSelect').get(0)).length,
        topics: []
      };
      topicDoms.each(function() {
        var authorAndRating, getAuthorAndRating, getMessageId, getNumberOfReplies, getTitle, getTotalNumberOfPage, messageId, numberOfReplies, title, totalNumberOfPage;
        getAuthorAndRating = function(ele) {
          var author, authorDom, rating, text;
          authorDom = $('.TopicBox_Author', ele);
          text = authorDom.text().trim();
          author = text.substring(0, text.indexOf("-"));
          author = author.trim();
          rating = parseInt(text.substring(text.lastIndexOf(":") + 2, text.lastIndexOf(")")));
          return {
            author: author,
            rating: rating
          };
        };
        getTitle = function(ele) {
          var titleDom;
          titleDom = $('a div:not(.TopicBox_Replies)', ele);
          return titleDom.text().trim();
        };
        getMessageId = function(ele) {
          var href, link;
          link = $('a', ele);
          href = link.attr('href');
          return href.substring(href.indexOf("=") + 1, href.lastIndexOf("&"));
        };
        getTotalNumberOfPage = function(ele) {
          var pageOptionsDom;
          pageOptionsDom = $('.TopicBox_PageSelect option', ele);
          return pageOptionsDom.length - 1;
        };
        getNumberOfReplies = function(ele) {
          var numberOfReplies;
          numberOfReplies = $('.TopicBox_Replies', ele);
          return numberOfReplies = parseInt(numberOfReplies.text().trim());
        };
        authorAndRating = getAuthorAndRating(this);
        title = getTitle(this);
        messageId = getMessageId(this);
        totalNumberOfPage = getTotalNumberOfPage(this);
        numberOfReplies = getNumberOfReplies(this);
        return result.topics.push({
          author: authorAndRating.author,
          rating: authorAndRating.rating,
          title: title,
          messageId: messageId,
          totalNumberOfPage: totalNumberOfPage,
          numberOfReplies: numberOfReplies
        });
      });
      return onCompleteCallback(result);
    };

    return TopicListParser;

  })();

  module.exports = TopicListParser;

}).call(this);

//# sourceMappingURL=TopicListParser.map
