// Generated by CoffeeScript 1.7.1
(function() {
  var MobileGoldenParser, ThreadParser, TopicListParser, TypeParser;

  TopicListParser = require('./parser/TopicListParser');

  ThreadParser = require('./parser/ThreadParser');

  TypeParser = require('./parser/TypeParser');

  MobileGoldenParser = (function() {
    function MobileGoldenParser() {}

    MobileGoldenParser.prototype.parseTopicList = function(responseBody, onCompleteCallback) {
      return new TopicListParser().parse(responseBody, onCompleteCallback);
    };

    MobileGoldenParser.prototype.parseThread = function(responseBody, onCompleteCallback) {
      return new ThreadParser().parse(responseBody, onCompleteCallback);
    };

    MobileGoldenParser.prototype.parseTypes = function(responseBody, onCompleteCallback) {
      return new TypeParser().parse(responseBody, onCompleteCallback);
    };

    return MobileGoldenParser;

  })();

  module.exports = MobileGoldenParser;

}).call(this);

//# sourceMappingURL=MobileGoldenParser.map
