// Generated by CoffeeScript 1.7.1
(function() {
  var ThreadParser, cheerio, domainList;

  cheerio = require("cheerio");

  domainList = ['m1', 'm2', 'm3'];

  ThreadParser = (function() {
    function ThreadParser() {}

    ThreadParser.prototype.parse = function(responseBody, onCompleteCallback) {
      var $, replies, result, subDomain;
      $ = cheerio.load(responseBody);
      subDomain = domainList[Math.floor(Math.random() * domainList.length)];
      result = [];
      result.isNextPageAvailable = $('.View_PageSelectRight').text().trim() !== '';
      result.isPreviousPageAvailable = $('.View_PageSelectLeft').text().trim() !== '';
      result.totalNumberOfPage = $('option', $('select.View_PageSelect').get(0)).length - 2;
      result.title = $('.ViewTitle').text().trim();
      replies = $('.ReplyBox');
      replies.each(function() {
        var author, authorDom, contentDom, date, gender, images, prependDomainToImageSrc;
        prependDomainToImageSrc = function(img) {
          var src;
          src = img.attr('src');
          return img.attr('src', "http://" + subDomain + ".hkgolden.com" + src);
        };
        authorDom = $('.ViewNameMale, .ViewNameFemale', this);
        if (authorDom.length > 0) {
          author = authorDom.text();
          gender = $('.ViewNameMale', this).length > 0 ? "male" : "female";
          date = $('.ViewDate', this).text().trim();
          contentDom = $($(this).children('div').get(1));
          $('img[src^="/faces"]', contentDom).each(function() {
            return prependDomainToImageSrc($(this));
          });
          images = [];
          $('img.Image', contentDom).each(function() {
            var $this, imageSrc;
            $this = $(this);
            $this.removeAttr('onclick');
            prependDomainToImageSrc($this);
            imageSrc = $this.attr('alt');
            imageSrc = imageSrc.substring(imageSrc.indexOf(']') + 1, imageSrc.lastIndexOf('['));
            $this.attr('ng-src', imageSrc);
            return images.push(imageSrc);
          });
          return result.push({
            author: author,
            gender: gender,
            content: contentDom.html(),
            images: images,
            date: date
          });
        }
      });
      return onCompleteCallback(result);
    };

    return ThreadParser;

  })();

  module.exports = ThreadParser;

}).call(this);

//# sourceMappingURL=ThreadParser.map
