// Generated by CoffeeScript 1.7.1
(function() {
  var ThreadParser, cheerio;

  cheerio = require("cheerio");

  ThreadParser = (function() {
    function ThreadParser() {}

    ThreadParser.prototype.parse = function(responseBody, onCompleteCallback) {
      var $, replies, result;
      $ = cheerio.load(responseBody);
      replies = $('.ReplyBox');
      result = [];
      replies.each(function() {
        var author, authorDom, contentDom, gender, images;
        authorDom = $('.ViewNameMale, .ViewNameFemale', this);
        if (authorDom.length > 0) {
          author = authorDom.text();
          gender = $('.ViewNameMale', this).length > 0 ? "male" : "female";
          contentDom = $($(this).children('div').get(1));
          images = [];
          $('img.Image', contentDom).each(function() {
            var imageSrc;
            imageSrc = $(this).attr('alt');
            imageSrc = imageSrc.substring(imageSrc.indexOf(']') + 1, imageSrc.lastIndexOf('['));
            return images.push(imageSrc);
          });
          return result.push({
            author: author,
            gender: gender,
            content: contentDom.html(),
            images: images
          });
        }
      });
      return onCompleteCallback(result);
    };

    return ThreadParser;

  })();

  module.exports = ThreadParser;

}).call(this);

//# sourceMappingURL=ThreadParser.map
